version: '3'
services:
  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "3001:3001"
    networks:
      - network

  # frontend:
  #   image: tzuhsun/stylish-frontend
  #   container_name: stylish-frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REACT_APP_API_BASE_URL=https://tzuhsun.online/api
  #   networks:
  #     - network

  nginx:
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - server
      # - frontend

networks:
  network:
    driver: bridge